name: publish python package to PyPI

on:
  release:
    types: [published]

jobs:
  build_wheels:
    name: Build wheels
    runs-on: ubuntu-latest
    environment: pypi
    steps:
      - uses: actions/checkout@master

      - name: Set up Python
        uses: actions/setup-python@v1

      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
          .

      - name: publish to PYPI
        uses: pypa/gh-action-pypi-publish@v1.8.12
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
